import { Fragment, useId, useState } from 'react'
import { caseStudies, caseStudyGroups, type CaseStudy } from '../content'
import { PortfolioImage } from './PortfolioImage'
import { Reveal, Section, SectionHeading, Stat } from './ui'

const visualById: Record<string,{src:string;alt:string}> = {
  baja:{src:'images/baja-team.jpg',alt:'Team Predators Racing BAJA team'},
  factoryflow:{src:'images/factoryflow-dashboard.png',alt:'FactoryFlow AI manufacturing dashboard'},
}

function EvidenceVisual({cs}:{cs:CaseStudy}) {
  if (cs.id === 'dmaic') return <div className="exhibit-visual"><div className="stat text-[9px] uppercase tracking-[.2em] text-accent">Before / after · 12 weeks</div><div className="mt-8 space-y-7"><div><div className="mb-3 flex items-end justify-between"><span className="text-xs font-medium">Resource utilisation</span><b className="stat text-sm">70 → 91%</b></div><div className="grid grid-cols-2 gap-3"><div><div className="mb-1 stat text-[9px] text-faint">BEFORE · 70%</div><div className="h-3 bg-surface-2"><div className="h-full w-[70%] bg-line"/></div></div><div><div className="mb-1 stat text-[9px] text-accent">AFTER · 91%</div><div className="h-3 bg-surface-2"><div className="metric-bar h-full w-[91%] bg-accent"/></div></div></div></div><div><div className="mb-3 flex items-end justify-between"><span className="text-xs font-medium">Monthly profit</span><b className="stat text-sm">₹4.5L → ₹5.15L</b></div><div className="grid grid-cols-2 gap-3"><div><div className="mb-1 stat text-[9px] text-faint">BEFORE · ₹4.5L</div><div className="h-3 bg-surface-2"><div className="h-full w-[87.4%] bg-line"/></div></div><div><div className="mb-1 stat text-[9px] text-accent">AFTER · ₹5.15L</div><div className="metric-bar h-full w-full bg-ink"/></div></div></div></div><div className="mt-8 grid grid-cols-3 gap-3 border-t border-line pt-5">{[['-17%','lead time'],['-13.4%','material waste'],['+7.12%','quarterly revenue']].map(x=><div key={x[1]}><div className="stat text-xl font-semibold">{x[0]}</div><div className="mt-1 text-[9px] uppercase tracking-wider text-faint">{x[1]}</div></div>)}</div></div>
  if (cs.id === 'arai') return <div className="exhibit-visual"><div className="stat text-[9px] uppercase tracking-[.2em] text-accent">EV compliance operating system</div><div className="relative mt-7 grid grid-cols-3 gap-3"><div className="absolute left-[16%] right-[16%] top-1/2 h-px bg-accent/50"/>{[['01','Standards','IS 17017 / IEC 61851'],['02','Test','DC EMC + charger compliance'],['03','Deliver','Statement / certification']].map(x=><div key={x[0]} className="relative z-10 bg-surface p-4 text-center"><div className="stat text-[9px] text-accent">{x[0]}</div><div className="mt-3 text-sm font-semibold">{x[1]}</div><div className="mt-1 text-[10px] leading-4 text-muted">{x[2]}</div></div>)}</div><div className="mt-7 grid grid-cols-3 gap-3 border-t border-line pt-5">{[['500+','programs'],['+20%','throughput'],['-15%','turnaround']].map(x=><div key={x[1]}><div className="stat text-xl font-semibold">{x[0]}</div><div className="mt-1 text-[9px] uppercase tracking-wider text-faint">{x[1]}</div></div>)}</div></div>
  if (cs.id === 'baja') { const v=visualById.baja; return <div className="image-frame aspect-[16/10]"><img src={v.src} alt={v.alt} className="h-full w-full object-cover"/><div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/75 to-transparent p-5 pt-16"><div className="stat text-[9px] uppercase tracking-[.18em] text-white/75">BAJA SAE / Team Predators Racing</div><div className="mt-1 text-sm font-medium text-white">Build · fund · pitch · race</div></div></div> }
  if (cs.id === 'voltedge') return <div className="exhibit-visual"><div className="stat text-[9px] uppercase tracking-[.2em] text-accent">Market-entry decision matrix</div><div className="mt-6 grid grid-cols-2 gap-px border border-line bg-line">{[['GREENFIELD','Own certification + plant','High fixed cost'],['CONTRACT MFG','Fast India entry','Less process control'],['JV','Local access + partner','Shared economics'],['ACQUISITION','Buy capability','Integration risk']].map(x=><div key={x[0]} className="bg-surface p-4"><div className="stat text-[9px] text-accent">{x[0]}</div><div className="mt-3 text-sm font-semibold">{x[1]}</div><div className="mt-1 text-[10px] text-muted">{x[2]}</div></div>)}</div><div className="mt-5 text-xs text-muted">Case architecture: market sizing → customer segmentation → capability gaps → entry mode.</div></div>
  if (cs.id === 'governance') return <div className="exhibit-visual"><div className="stat text-[9px] uppercase tracking-[.2em] text-accent">The Maharashtra Urban Adoption Compact</div><div className="mt-7 grid grid-cols-5 gap-1">{['Discover','Validate','Approve','Buy','Scale'].map((x,i)=><div key={x} className="border border-line bg-surface-2 p-3 text-center"><div className="stat text-[9px] text-accent">0{i+1}</div><div className="mt-4 text-xs font-semibold">{x}</div></div>)}</div><div className="mt-6 border-l-2 border-accent pl-4 text-xs leading-5 text-muted">“The constraint is not capital. It is the missing pathway from a validated solution to a first government order.”</div></div>
  if (cs.id === 'factoryflow') { const v=cs.image; return v ? <div className="image-frame aspect-[16/10]"><img src={v.src} alt={v.alt} className="h-full w-full object-cover object-left"/></div> : null }
  return <div className="exhibit-visual"><div className="stat text-[9px] uppercase tracking-[.2em] text-accent">Exhibit</div><div className="mt-6 text-4xl font-semibold tracking-[-.05em]">{cs.headlineStat.value}</div><div className="mt-2 max-w-xs text-sm text-muted">{cs.headlineStat.label}</div></div>
}

function stepsOf(cs:CaseStudy){ return cs.steps ?? [{label:'Situation',text:cs.situation??''},{label:'Approach',text:cs.approach??''},{label:'Result',text:cs.result??''}] }

function Card({cs,defaultOpen=false,flip=false}:{cs:CaseStudy;defaultOpen?:boolean;flip?:boolean}) {
 const [open,setOpen]=useState(defaultOpen); const panelId=useId()
 return <Reveal className="group"><article className="border-y border-line py-10 lg:py-14">
  <div className={`grid items-center gap-10 lg:grid-cols-2 lg:gap-20 ${flip?'lg:[&>div:first-child]:order-2':''}`}>
   <div><div className="flex items-center gap-3"><span className="stat text-sm text-accent">{cs.index}</span><span className="h-px w-8 bg-line"/><span className="text-[9px] uppercase tracking-[.18em] text-faint">{cs.frameLabel}</span></div><h3 className="mt-5 max-w-xl text-[clamp(2rem,4vw,3.4rem)] font-semibold leading-[.95] tracking-[-.055em]">{cs.title}</h3><div className="mt-7"><Stat value={cs.headlineStat.value} label={cs.headlineStat.label} size="lg"/></div><button type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls={panelId} className="btn btn-secondary mt-7">{open?'Close detail':'Read case'}<span className="ml-2">{open?'↑':'↓'}</span></button></div>
   <EvidenceVisual cs={cs}/>
  </div>
  {open&&<div id={panelId} className="mt-10 border-t border-line pt-2">{stepsOf(cs).map((s,i)=><Fragment key={s.label}>{i>0&&<div className="scale-bar my-1"/>}<div className="grid gap-2 py-5 sm:grid-cols-[110px_1fr] sm:gap-8"><div className="stat text-[9px] uppercase tracking-[.18em] text-accent">{s.label}</div><p className="max-w-3xl text-sm leading-7 text-muted">{s.text}</p></div></Fragment>)}{cs.callout&&<div className="mt-4 border-l-2 border-accent bg-surface-2 px-5 py-4"><div className="stat text-[9px] uppercase tracking-[.18em] text-accent">{cs.callout.label}</div><p className="mt-1 text-sm leading-6">{cs.callout.text}</p></div>}{cs.image&&cs.id!=='factoryflow'&&<PortfolioImage {...cs.image} className="mt-6"/>}<ul className="mt-8 grid gap-6 border-t border-line pt-7 sm:grid-cols-3">{cs.metrics.map(m=><li key={m.label}><Stat value={m.value} label={m.label} size="sm"/></li>)}</ul>{cs.link&&<a href={cs.link.href} target="_blank" rel="noreferrer" className="btn btn-secondary mt-7">{cs.link.label}</a>}</div>}
 </article></Reveal>
}

function GroupLabel({children}:{children:React.ReactNode}){return <div className="flex items-center gap-4"><span className="stat shrink-0 text-[9px] uppercase tracking-[.2em] text-faint">{children}</span><div className="scale-bar flex-1"/></div>}

export default function CaseStudies(){
 const visible=caseStudies.filter(cs=>cs.id!=='treasurebox')
 return <Section id="work"><SectionHeading index="03" title="Case Studies" lede="A small set of projects where the work, method and measurable outcome can be shown without a wall of text."/><div className="space-y-10">{(['professional','academic'] as const).map(group=>{const items=visible.filter(cs=>cs.group===group);if(!items.length)return null;return <div key={group} className="space-y-3"><GroupLabel>{caseStudyGroups[group]}</GroupLabel>{items.map((cs,i)=><Card key={cs.id} cs={cs} defaultOpen={group==='professional'&&i===0} flip={i%2===1}/>)}</div>})}</div></Section>
}
